### PR TITLE
Update StructFuseOperations.java

### PR DESCRIPTION
**Pull request by btiernay**
Fix for `read_buf` and `write_buf` being called when they are not implemented.

### CODE REVIEW

**Comment by pron** [comment]
Thank you very much!
I'll gladly merge this, but I'd ask you to kindly match the current formatting and leave the import statments alone, or it's really hard to see what you've done.

**Comment by btiernay** [comment]
Sorry about that, will fix. Darn workspace formatter in Eclipse.

**Comment by btiernay** [comment]
Fixed.

**Comment by pron** [comment]
Thanks!

**Pull request merged**
